config/routes.rb
Sample::Application.routes.draw do

  resources :books
  resources :hello
  resources :kakiko
  resources :ita

  match ':controller(/:action(/:id))(.:format)'
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :price, :publish, :title
end

app/models/hello.rb
class Hello < ActiveRecord::Base
  attr_accessible :hoge
end

app/models/ita.rb
class Ita < ActiveRecord::Base
  attr_accessible :ita_id, :title
  validates :title,
  	:presence => true
end

app/models/kakiko.rb
class Kakiko < ActiveRecord::Base
  attr_accessible :ita_id, :kakikomi, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/hello_controller.rb
# coding: utf-8

class HelloController < ApplicationController
#  def index
#    render :text => 'こんにちは世界！'
#    @message = 'こんにちは世界！'
#  end
  def index
    @hello = Hello.new
    @hello.hoge = 'aaaaaa'
    @hello.save
  
    @hellos = Hello.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hellos }
    end
  end
end

app/controllers/ita_controller.rb
class ItaController < ApplicationController
  def index
    @itas = Ita.all
  end

  def create
  	@ita = Ita.new(params[:ita])
  	respond_to do |format|
	  	if @ita.save
	  		format.html { redirect_to(:controller => 'kakiko', :action => 'index', :id => @ita.id)}
	  	else
	  		format.html { render :action => 'create'}
	  	end
	  end
  end
end

app/controllers/kakiko_controller.rb
# coding: utf-8
class KakikoController < ApplicationController
  def index
    @kakikos = Kakiko.where('ita_id = ?', params[:id]).order('created_at desc')
    @kakiko = Kakiko.new
    @kakiko.ita_id = params[:id]
    @ita = Ita.new
  end

  def create
  	@kakiko = Kakiko.new(params[:kakiko])
  	respond_to do |format|
	  	if @kakiko.save
	  		format.html { redirect_to( :action => 'index', :id => @kakiko.ita_id)}
	  	else
	  		format.html { render controller => 'ita', :action => 'index'}
	  	end
	  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/ita_helper.rb
module ItaHelper
end

app/helpers/kakiko_helper.rb
module KakikoHelper
	def hbr(str)
		h(str).gsub(/(\r\n?)|(\n)/, "<br />").html_safe
	end
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_field :publish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Publish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.price %></td>
    <td><%= book.publish %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<p>
  <b>Publish:</b>
  <%= @book.publish %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/hello/index.html.erb
<br>
----------------------------------<br>
<% @hellos.each do |hello| %>
    <%= hello.hoge %><br>
<% end %>
----------------------------------<br>

app/views/ita/create.html.erb
<%= form_tag({:controller => 'ita', :action => 'create'}) do %>
	<div class="field">
		<table>
			<tr>
				<td>
					タイトル<%= text_field :ita ,:title, {:size => "25"} %>
				</td>
				<td>
					<%= submit_tag '新規スレッド' %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/ita/index.html.erb
<div class="content">
	<table class="table-main">
		<% @itas.each_with_index do |ita, i| %>
			<tr>
				<td>
					<%= i + 1 %>
					<%= link_to(ita.title, :controller => 'kakiko', :action => 'index', :id => ita.id) %>
				</td>
		<% end %>
	</table>
</div>

app/views/kakiko/index.html.erb
<%= form_tag({:controller => 'kakiko', :action => 'create'}) do %>
	<div class="field">
		<%= text_area :kakiko , :kakikomi, {:size => "25x5",:maxlength => 180} %>
		<%= hidden_field :kakiko, :ita_id %>
		<%= submit_tag 'かきかき' %>
	</div>
<% end %>
<div class="content">
	<table class="table-main">
		<% @kakikos.each_with_index do |kakiko, i| %>
			<tr>
				<td>
					<%= i + 1 %>
				</td>
				<td>
					<%= kakiko.created_at.strftime("%Y-%m-%d(#{%w(日 月 火 水 木 金 土)[kakiko.created_at.wday]}) %H:%M:%S") %>
				</td>
			<tr>
				<td colspan="2" class="comment"><%= hbr(kakiko.kakikomi) %></td>
		<% end %>
	</table>
</div>

<%= render :file => "/ita/create" %>
<%= link_to 'top', ita_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>